before:
  hooks:
    - go mod tidy

builds:

- main: cmd/nuclei/main.go
  binary: nuclei
  id: nuclei-cli

  env:
  - CGO_ENABLED=0

  goos: [windows,linux,darwin]
  goarch: [amd64,386,arm,arm64]
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

  flags:
    - -trimpath

- main: cmd/cve-annotate/main.go
  binary: cve-annotate
  id: annotate

  env:
  - CGO_ENABLED=0

  goos: [linux]
  goarch: [amd64]

archives:
- format: zip
  id: nuclei
  builds: [nuclei-cli]
  replacements:
      darwin: macOS

- format: zip
  id: annotate
  builds: [annotate]
  name_template: "{{ .Binary }}"

checksum:
  algorithm: sha256

snapcrafts:
  - id: nuclei
    replacements:
      darwin: macOS
    name: nuclei
    publish: false
    summary: Fast and customisable vulnerability scanner based on simple YAML based DSL.
    description: |
      Nuclei is used to send requests across targets based on a template, leading to zero false positives and providing fast scanning on a large number of hosts. Nuclei offers scanning for a variety of protocols, including TCP, DNS, HTTP, SSL, File, Whois, Websocket, Headless etc. With powerful and flexible templating, Nuclei can be used to model all kinds of security checks.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      nuclei:
        command: nuclei
        plugs:
          - home
          - network
          - removable-media
          - dot-nuclei
    plugs:
      dot-nuclei:
        interface: personal-files
        write:
          - $HOME/.config/nuclei
          - $HOME/nuclei-templates